<?php

namespace PhillPrice\ResumeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
	public function findAllOrderedByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM PhillPriceResumeBundle:Experience e ORDER BY e.current DESC, e.end_date DESC'
            )
            ->getResult();
    }
}
